blank_issues_enabled: true
contact_links:
  - name: Medical or behavior emergency
    url: https://www.dacvb.org/search/custom.asp?id=5985
    about: This project cannot provide emergency or in-person care.
